"""Persistence helpers for AI-generated practice materials."""

from sqlmodel import select

from ..tables.practice_material import PracticeMaterial
from .base_repository import BaseRepository


class PracticeMaterialRepository(BaseRepository[PracticeMaterial, int]):
    """Provides persistence for practice materials generated from exam uploads."""

    @property
    def model_type(self) -> type[PracticeMaterial]:
        """Returns the SQLModel class managed by this repository."""
        return PracticeMaterial

    def get_by_upload_id(self, upload_id: int) -> PracticeMaterial | None:
        """Returns the practice material generated for a specific exam upload.

        Args:
            upload_id: Identifier of the exam PDF upload record.

        Returns:
            Matching practice material when found; otherwise ``None``.
        """
        stmt = select(PracticeMaterial).where(PracticeMaterial.upload_id == upload_id)
        return self._session.exec(stmt).first()

    def list_by_student_and_course(self, student_pid: int, course_id: int) -> list[PracticeMaterial]:
        """Returns all practice materials generated by a student in a course.

        Args:
            student_pid: PID of the student.
            course_id: Identifier of the course.

        Returns:
            List of practice materials ordered by most recently generated first.
        """
        stmt = (
            select(PracticeMaterial)
            .where(PracticeMaterial.student_pid == student_pid)
            .where(PracticeMaterial.course_id == course_id)
            .order_by(PracticeMaterial.generated_at.desc())  # type: ignore[arg-type]
        )
        return list(self._session.exec(stmt).all())
